version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./html/:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esr
      # MYSQL_USER: myuser1
      # MYSQL_PASSWORD: mypassword
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
